// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage_Command int32

const (
	ControlMessage_PING            ControlMessage_Command = 0
	ControlMessage_START_SYNC      ControlMessage_Command = 1
	ControlMessage_STOP_SYNC       ControlMessage_Command = 2
	ControlMessage_TEST_CONNECTION ControlMessage_Command = 3
)

// Enum value maps for ControlMessage_Command.
var (
	ControlMessage_Command_name = map[int32]string{
		0: "PING",
		1: "START_SYNC",
		2: "STOP_SYNC",
		3: "TEST_CONNECTION",
	}
	ControlMessage_Command_value = map[string]int32{
		"PING":            0,
		"START_SYNC":      1,
		"STOP_SYNC":       2,
		"TEST_CONNECTION": 3,
	}
)

func (x ControlMessage_Command) Enum() *ControlMessage_Command {
	p := new(ControlMessage_Command)
	*p = x
	return p
}

func (x ControlMessage_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessage_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (ControlMessage_Command) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x ControlMessage_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessage_Command.Descriptor instead.
func (ControlMessage_Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2, 0}
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentToken    string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	NodeCode      string                 `protobuf:"bytes,2,opt,name=node_code,json=nodeCode,proto3" json:"node_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // e.g., "IDLE", "SYNCING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *Heartbeat) GetNodeCode() string {
	if x != nil {
		return x.NodeCode
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConnectionTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Latency       string                 `protobuf:"bytes,4,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestResult) Reset() {
	*x = ConnectionTestResult{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestResult) ProtoMessage() {}

func (x *ConnectionTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestResult.ProtoReflect.Descriptor instead.
func (*ConnectionTestResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionTestResult) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ConnectionTestResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionTestResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConnectionTestResult) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           ControlMessage_Command `protobuf:"varint,1,opt,name=cmd,proto3,enum=agent.ControlMessage_Command" json:"cmd,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON containing Job Details
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMessage) GetCmd() ControlMessage_Command {
	if x != nil {
		return x.Cmd
	}
	return ControlMessage_PING
}

func (x *ControlMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ControlMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DataBatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DataBatch) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataBatch) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DataBatch) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,3,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResult) Reset() {
	*x = SyncResult{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResult) ProtoMessage() {}

func (x *SyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResult.ProtoReflect.Descriptor instead.
func (*SyncResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SyncResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResult) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *SyncResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"a\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12\x1b\n" +
	"\tnode_code\x18\x02 \x01(\tR\bnodeCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x88\x01\n" +
	"\x14ConnectionTestResult\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\alatency\x18\x04 \x01(\tR\alatency\"\xbb\x01\n" +
	"\x0eControlMessage\x12/\n" +
	"\x03cmd\x18\x01 \x01(\x0e2\x1d.agent.ControlMessage.CommandR\x03cmd\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"G\n" +
	"\aCommand\x12\b\n" +
	"\x04PING\x10\x00\x12\x0e\n" +
	"\n" +
	"START_SYNC\x10\x01\x12\r\n" +
	"\tSTOP_SYNC\x10\x02\x12\x13\n" +
	"\x0fTEST_CONNECTION\x10\x03\"{\n" +
	"\tDataBatch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12\x1e\n" +
	"\x04rows\x18\x04 \x03(\v2\n" +
	".agent.RowR\x04rows\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x87\x01\n" +
	"\n" +
	"SyncResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rrows_affected\x18\x03 \x01(\x03R\frowsAffected\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\a\n" +
	"\x05Empty2\xb5\x01\n" +
	"\tSyncAgent\x126\n" +
	"\aSession\x12\x10.agent.Heartbeat\x1a\x15.agent.ControlMessage(\x010\x01\x121\n" +
	"\bPushData\x12\x10.agent.DataBatch\x1a\x11.agent.SyncResult(\x01\x12=\n" +
	"\x10ReportTestResult\x12\x1b.agent.ConnectionTestResult\x1a\f.agent.EmptyB\x18Z\x16./internal/agent/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_agent_proto_goTypes = []any{
	(ControlMessage_Command)(0),  // 0: agent.ControlMessage.Command
	(*Heartbeat)(nil),            // 1: agent.Heartbeat
	(*ConnectionTestResult)(nil), // 2: agent.ConnectionTestResult
	(*ControlMessage)(nil),       // 3: agent.ControlMessage
	(*DataBatch)(nil),            // 4: agent.DataBatch
	(*Row)(nil),                  // 5: agent.Row
	(*SyncResult)(nil),           // 6: agent.SyncResult
	(*Empty)(nil),                // 7: agent.Empty
}
var file_proto_agent_proto_depIdxs = []int32{
	0, // 0: agent.ControlMessage.cmd:type_name -> agent.ControlMessage.Command
	5, // 1: agent.DataBatch.rows:type_name -> agent.Row
	1, // 2: agent.SyncAgent.Session:input_type -> agent.Heartbeat
	4, // 3: agent.SyncAgent.PushData:input_type -> agent.DataBatch
	2, // 4: agent.SyncAgent.ReportTestResult:input_type -> agent.ConnectionTestResult
	3, // 5: agent.SyncAgent.Session:output_type -> agent.ControlMessage
	6, // 6: agent.SyncAgent.PushData:output_type -> agent.SyncResult
	7, // 7: agent.SyncAgent.ReportTestResult:output_type -> agent.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
