// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncAgent_Session_FullMethodName  = "/agent.SyncAgent/Session"
	SyncAgent_PushData_FullMethodName = "/agent.SyncAgent/PushData"
)

// SyncAgentClient is the client API for SyncAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncAgentClient interface {
	// Agent connects and waits for commands (Heartbeat + Job relay)
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, ControlMessage], error)
	// Agent pushes data to Master during a sync job
	PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataBatch, SyncResult], error)
}

type syncAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncAgentClient(cc grpc.ClientConnInterface) SyncAgentClient {
	return &syncAgentClient{cc}
}

func (c *syncAgentClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncAgent_ServiceDesc.Streams[0], SyncAgent_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncAgent_SessionClient = grpc.BidiStreamingClient[Heartbeat, ControlMessage]

func (c *syncAgentClient) PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataBatch, SyncResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncAgent_ServiceDesc.Streams[1], SyncAgent_PushData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataBatch, SyncResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncAgent_PushDataClient = grpc.ClientStreamingClient[DataBatch, SyncResult]

// SyncAgentServer is the server API for SyncAgent service.
// All implementations must embed UnimplementedSyncAgentServer
// for forward compatibility.
type SyncAgentServer interface {
	// Agent connects and waits for commands (Heartbeat + Job relay)
	Session(grpc.BidiStreamingServer[Heartbeat, ControlMessage]) error
	// Agent pushes data to Master during a sync job
	PushData(grpc.ClientStreamingServer[DataBatch, SyncResult]) error
	mustEmbedUnimplementedSyncAgentServer()
}

// UnimplementedSyncAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncAgentServer struct{}

func (UnimplementedSyncAgentServer) Session(grpc.BidiStreamingServer[Heartbeat, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedSyncAgentServer) PushData(grpc.ClientStreamingServer[DataBatch, SyncResult]) error {
	return status.Error(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedSyncAgentServer) mustEmbedUnimplementedSyncAgentServer() {}
func (UnimplementedSyncAgentServer) testEmbeddedByValue()                   {}

// UnsafeSyncAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncAgentServer will
// result in compilation errors.
type UnsafeSyncAgentServer interface {
	mustEmbedUnimplementedSyncAgentServer()
}

func RegisterSyncAgentServer(s grpc.ServiceRegistrar, srv SyncAgentServer) {
	// If the following call panics, it indicates UnimplementedSyncAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncAgent_ServiceDesc, srv)
}

func _SyncAgent_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncAgentServer).Session(&grpc.GenericServerStream[Heartbeat, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncAgent_SessionServer = grpc.BidiStreamingServer[Heartbeat, ControlMessage]

func _SyncAgent_PushData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncAgentServer).PushData(&grpc.GenericServerStream[DataBatch, SyncResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncAgent_PushDataServer = grpc.ClientStreamingServer[DataBatch, SyncResult]

// SyncAgent_ServiceDesc is the grpc.ServiceDesc for SyncAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.SyncAgent",
	HandlerType: (*SyncAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _SyncAgent_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushData",
			Handler:       _SyncAgent_PushData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
