// Code generated by manual stub. 
package pb

import (
	"context"
	"encoding/json"
	"google.golang.org/grpc"
	"google.golang.org/grpc/encoding"
)

// JSON Codec Registration (To bypass protoc requirement)
func init() {
	encoding.RegisterCodec(&jsonCodec{})
}

type jsonCodec struct{}

func (c *jsonCodec) Marshal(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

func (c *jsonCodec) Unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

func (c *jsonCodec) Name() string {
	return "json"
}

// Helper to satisfy proto.Message interface
type protoMessage struct{}
func (*protoMessage) ProtoMessage() {}
func (*protoMessage) Reset()        {}
func (*protoMessage) String() string { return "" }

type AgentRegistrationRequest struct {
	protoMessage
	AgentId   string `json:"agent_id"`
	Hostname  string `json:"hostname"`
	IpAddress string `json:"ip_address"`
}

type AgentRegistrationResponse struct {
	protoMessage
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type HeartbeatRequest struct {
	protoMessage
	AgentId string `json:"agent_id"`
	Status  string `json:"status"`
}

type HeartbeatResponse struct {
	protoMessage
	Acknowledged bool `json:"acknowledged"`
}

type LogMessage struct {
	protoMessage
	AgentId   string `json:"agent_id"`
	JobId     string `json:"job_id"`
	Level     string `json:"level"`
	Message   string `json:"message"`
	Timestamp int64  `json:"timestamp"`
}

type LogAck struct {
	protoMessage
	Received int32 `json:"received"`
}

// MasterAgentServiceServer defines the server interface
type MasterAgentServiceServer interface {
	RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedMasterAgentServiceServer()
}

type UnimplementedMasterAgentServiceServer struct{}

func (UnimplementedMasterAgentServiceServer) RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error) {
	return nil, nil
}
func (UnimplementedMasterAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, nil
}
func (UnimplementedMasterAgentServiceServer) mustEmbedUnimplementedMasterAgentServiceServer() {}

func RegisterMasterAgentServiceServer(s *grpc.Server, srv MasterAgentServiceServer) {
	// Simple manual registration logic for the sake of the stub
	s.RegisterService(&_MasterAgentService_serviceDesc, srv)
}

var _MasterAgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MasterAgentService",
	HandlerType: (*MasterAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _MasterAgentService_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MasterAgentService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/master_agent.proto",
}

func _MasterAgentService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterAgentServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MasterAgentService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterAgentServiceServer).RegisterAgent(ctx, req.(*AgentRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterAgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterAgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MasterAgentService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterAgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Client Implementation
type MasterAgentServiceClient interface {
	RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type masterAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterAgentServiceClient(cc grpc.ClientConnInterface) MasterAgentServiceClient {
	return &masterAgentServiceClient{cc}
}

func (c *masterAgentServiceClient) RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error) {
	out := new(AgentRegistrationResponse)
	opts = append(opts, grpc.CallContentSubtype("json"))
	err := c.cc.Invoke(ctx, "/pb.MasterAgentService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterAgentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	opts = append(opts, grpc.CallContentSubtype("json"))
	err := c.cc.Invoke(ctx, "/pb.MasterAgentService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
