services:
  # db:
  #   image: postgres:15-alpine
  #   container_name: syncgo-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: B1ntang12!@#
  #     POSTGRES_DB: dsp
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U postgres -d dsp" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: syncgo-backend
    environment:
      - PORT=8080
      - GRPC_PORT=9090
      - DATABASE_URL=postgres://postgres:3w6%25JPcClvS%24_pGSQL@117.53.44.215:5324/dsp?sslmode=disable
      - JWT_SECRET=supersecret-dsp-key-change-in-production
      - TLS_ENABLED=true
      - TLS_CA_PATH=/app/certs/ca.crt
      - TLS_CERT_PATH=/app/certs/server.crt
      - TLS_KEY_PATH=/app/certs/server.key
    volumes:
      - ./certs:/app/certs:ro
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      cert-gen:
        condition: service_completed_successfully
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api/v1
    container_name: syncgo-frontend
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
    depends_on:
      - backend
    restart: unless-stopped

  agent:
    build:
      context: ./backend
      dockerfile: Dockerfile.agent
    container_name: syncgo-agent
    environment:
      - TOKEN=agent-secret-123
      - NODE_CODE=DOCKER_AGENT_01
      - MASTER_ADDR=backend:9090
      - TLS_ENABLED=true
      - TLS_CA_PATH=/app/certs/ca.crt
      - TLS_CERT_PATH=/app/certs/client.crt
      - TLS_KEY_PATH=/app/certs/client.key
      - DB_DRIVER=postgres
      - DB_URL=postgres://postgres:3w6%25JPcClvS%24_pGSQL@117.53.44.215:5324/dsp?sslmode=disable
    volumes:
      - ./certs:/app/certs:ro
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      backend:
        condition: service_started
      cert-gen:
        condition: service_completed_successfully
    restart: unless-stopped

  cert-gen:
    image: golang:1.25-alpine
    container_name: syncgo-cert-gen
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "if [ ! -f certs/ca.crt ]; then
               echo 'Generating certificates...';
               go run scripts/gen_certs.go;
             else
               echo 'Certificates already exist.';
             fi"

  nginx:
    image: nginx:alpine
    container_name: syncgo-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  pgdata:
